<div id="contact_us_form" style="display:none">
   <div id="contact_us_container">
      <a href="#" class="close">X</a>
      <div class="intro">
         <h2>We Encourage Questions!</h2>
         <p>
            At Goldster, we always welcome customer feedback and inquiries. Our friendly staff will be happy to help you in any way they can.  Please feel free to contact via email or in person.  All info needed is below:
         </p>
      </div>
      
      <div class="body">
         <div class="left">
            <h4>Contact Info</h4>
            <p>
               Goldster<br />
               13176 N. Dale Mabry Hwy. Suite 605<br />
               Tampa, Florida, 33618
            </p>
            <p>
               <strong>Toll-Free Phone: 1-877-805-0811<br />
               E-Mail: <a href="mailto:info@goldster.com">info@goldster.com</a></strong>
            </p>
            <div class="map">
               <!-- <a href="#">Google</a> -->
               <img src="/images/contact_map.png" alt="Map" />
            </div>
         </div>
         <div class="right">
            <form action="#" method="post">
               <dl>
                  <dt><label for="name">Name:</label></dt>
                  <dd><input type="text" name="name" id="name" value="" /></dd>
                  
                  <dt><label for="email">Email:</label></dt>
                  <dd><input type="text" name="email" id="email" value="" /></dd>
                  
                  <dt><label for="name">Subject:</label></dt>
                  <dd>
                     <select name="subject">
                        <option value="Select A Topic">Select A Topic</option>
                        <option value="shipping">Shipping</option>
                        <option value="billing">Billing</option>
                        <option value="order_status">Order Status</option>
                     </select>
                  </dd>
                  
                  <dt><label for="message">Message:</label></dt>
                  <dd>
                     <textarea name="message"></textarea>
                  </dd>
                  
               </dl>
         		<input type="submit" name="submit" class="submit" value="Submit Your Question" />
            </form>
         </div>
      </div>
   </div>
   <div id="contact_us_wrapper"></div>
</div>