<div id="footer">
<div style="float:left; width:400px;">
      
    <p style="margin:0px; padding:0 0 10px 0; font:18px 'Trebuchet MS'; color:#333;">As Featured on:</p> 

     <img src="images/nbc_logo.png" alt="NBC" style="padding-right:10px;"/>
       <img src="images/fox_news.png" alt="Fox News" style="padding-right:10px;"/>
       <img src="images/usa_today.png" alt="Usa Today" style="padding-right:10px;"/>
      <img src="images/cnn.png" alt="CNN" />
     
       </div>


<div style="float:right; width:470px;"> 
  <div style="width:350px; float:left; "><ul class="social">
      <li>Get Social On Us</li>
      <li><a href="#" class="mail contact_popup">Mail</a></li>
      <li><a href="#" class="twitter">Twitter</a></li>
      <li><a href="#" class="facebook">Facebook</a></li>
   </ul></div>
   
   <div style="padding:20px 0 0 0; line-height:19px; float:right; width:470px">  <a href="./how_we_test_your_gold.php">How We Test Your Gold</a> | <a href="./affiliates.php">Affiliates</a> | <a href="./privacy.php">Privacy Policy</a> |  
       <a href="./terms.php">Terms of Service</a> | <a href="#" class="contact_popup">Contact Us</a>
  
      <br>
      Copyright &copy; 2008-2010 Prestige Gold Buyers
.com. All rights reserved.    </div>
   
    </div>
       
       
      
</div>
<!-- /footer -->