<div id="form">
	<form action="#" method="post">
	   
		<div class="first_step" style="display:block;">
		   <h2>Request Your FREE Gold Pack</h2>
         <div class="first_errors errors" style="display:none"></div>
			<dl>
				<dt><label for="first_name"><span>*</span> First Name:</label></dt>
				<dd><input type="text" name="first_name" id="first_name" value="" /></dd>
      
				<dt><label for="last_name"><span>*</span> Last Name:</label></dt>
				<dd><input type="text" name="last_name" id="last_name" value="" /></dd>
      
				<dt><label for="address"><span>*</span> Address:</label></dt>
				<dd><input type="text" name="address" id="address" value="" /></dd>
      
				<dt><label for="city"><span>*</span> City:</label></dt>
				<dd><input type="text" name="city" id="city" value="" /></dd>
      
				<dt><label for="state"><span>*</span> State:</label></dt>
				<dd>
               <select name="state">
               	<option value="AK">AK</option>
               	<option value="AL">AL</option>
               	<option value="AR">AR</option>
               	<option value="AZ">AZ</option>
               	<option value="CA">CA</option>
               	<option value="CO">CO</option>
               	<option value="CT">CT</option>
               	<option value="DC">DC</option>
               	<option value="DE">DE</option>
               	<option value="FL">FL</option>
               	<option value="GA">GA</option>
               	<option value="HI">HI</option>
               	<option value="IA">IA</option>
               	<option value="ID">ID</option>
               	<option value="IL">IL</option>
               	<option value="IN">IN</option>
               	<option value="KS">KS</option>
               	<option value="KY">KY</option>
               	<option value="LA">LA</option>
               	<option value="MA">MA</option>
               	<option value="MD">MD</option>
               	<option value="ME">ME</option>
               	<option value="MI">MI</option>
               	<option value="MN">MN</option>
               	<option value="MO">MO</option>
               	<option value="MS">MS</option>
               	<option value="MT">MT</option>
               	<option value="NC">NC</option>
               	<option value="ND">ND</option>
               	<option value="NE">NE</option>
               	<option value="NH">NH</option>
               	<option value="NJ">NJ</option>
               	<option value="NM">NM</option>
               	<option value="NV">NV</option>
               	<option value="NY">NY</option>
               	<option value="OH">OH</option>
               	<option value="OK">OK</option>
               	<option value="OR">OR</option>
               	<option value="PA">PA</option>
               	<option value="RI">RI</option>
               	<option value="SC">SC</option>
               	<option value="SD">SD</option>
               	<option value="TN">TN</option>
               	<option value="TX">TX</option>
               	<option value="UT">UT</option>
               	<option value="VA">VA</option>
               	<option value="VT">VT</option>
               	<option value="WA">WA</option>
               	<option value="WI">WI</option>
               	<option value="WV">WV</option>
               	<option value="WY">WY</option>
               </select>
				</dd>
            
				<dt class="zip_code"><label for="zip_code"><span>*</span> Zip:</label></dt>
				<dd><input type="text" name="zip_code" id="zip_code" value="" maxlength="5" /></dd>
		
				<dt><label for="phone"><span>*</span> Phone:</label></dt>
				<dd><input type="text" name="phone" id="phone" value="" /></dd>
		
				<dt><label for="email"><span>*</span> Email:</label></dt>
				<dd><input type="text" name="email" id="email" value="" /></dd>

			</dl>
			<input type="submit" name="submit" class="submit" value="Request Now - It's FREE!" />
		</div>
	</form>
</div>