<div id="top_bar">

<img src="images/phone.jpg" alt="ring" />
 <!--  <p class="customer_service" style=" background:color:#000; font-weight:bolder;"><font size="+2" style="color:#fff;">Customer Service &bull; <strong>1-877-805-0811</strong></font></p>-->
</div>
<!-- /top_bar -->

<div id="header">
   <h1><a href="./index.php"></a></h1>
   <ul id="navigation">
      <li class="home"><a href="./index.php"<?php if(isset($home)): ?> class="active"<?php endif; ?>>Home</a></li>
      <li class="process"><a href="./process.php"<?php if(isset($process)): ?> class="active"<?php endif; ?>>The Process</a></li>
      <li class="payouts"><a href="./payouts.php"<?php if(isset($payouts)): ?> class="active"<?php endif; ?>>Payouts</a></li>
      <li class="faq"><a href="./faq.php"<?php if(isset($faq)): ?> class="active"<?php endif; ?>>FAQ</a></li>
      <li class="about_us"><a href="./about.php"<?php if(isset($about)): ?> class="active"<?php endif; ?>>About Us</a></li>
      <li class="tracking">
         <a href="#">Tracking</a>
         <div class="dropdown" style="display:none">
            <form action="#" method="post" id="tracking_form">
               <p>
                  <strong>Track Your Package</strong><br />
                  Enter your package tracking ID for it's status.
               </p>
               <p>
                  <input type="text" name="tracking" id="tracking" value="" />
                  <span class="error" style="display:none;">Please enter a valid tracking number.</span>
               </p>
            
               <input type="submit" name="submit" class="submit" value="Track" />
            </form>
         </div>
      </li>
   </ul>
</div>